//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 關聯性中繼資料

[assembly: EdmRelationshipAttribute("WheatDBModel", "FK_tbMemberAndCard_tbCard", "tbCard", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BakeryOrder.tbCard), "tbMemberAndCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BakeryOrder.tbMemberAndCard), true)]
[assembly: EdmRelationshipAttribute("WheatDBModel", "FK_tbMemberAndCard_tbMember1", "tbMember", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BakeryOrder.tbMember), "tbMemberAndCard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BakeryOrder.tbMemberAndCard), true)]
[assembly: EdmRelationshipAttribute("WheatDBModel", "FK_tbMemberInfo_tbMember", "tbMember", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BakeryOrder.tbMember), "tbMemberInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BakeryOrder.tbMemberInfo), true)]
[assembly: EdmRelationshipAttribute("WheatDBModel", "FK_tbMemberScore_tbMember", "tbMember", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BakeryOrder.tbMember), "tbMemberScore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BakeryOrder.tbMemberScore), true)]

#endregion

namespace BakeryOrder
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class MemberDBEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'MemberDBEntities' 區段中找到的連接字串，初始化新的 MemberDBEntities 物件。
        /// </summary>
        public MemberDBEntities() : base("name=MemberDBEntities", "MemberDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MemberDBEntities 物件。
        /// </summary>
        public MemberDBEntities(string connectionString) : base(connectionString, "MemberDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MemberDBEntities 物件。
        /// </summary>
        public MemberDBEntities(EntityConnection connection) : base(connection, "MemberDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tbCard> tbCards
        {
            get
            {
                if ((_tbCards == null))
                {
                    _tbCards = base.CreateObjectSet<tbCard>("tbCards");
                }
                return _tbCards;
            }
        }
        private ObjectSet<tbCard> _tbCards;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tbMember> tbMembers
        {
            get
            {
                if ((_tbMembers == null))
                {
                    _tbMembers = base.CreateObjectSet<tbMember>("tbMembers");
                }
                return _tbMembers;
            }
        }
        private ObjectSet<tbMember> _tbMembers;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tbMemberAndCard> tbMemberAndCards
        {
            get
            {
                if ((_tbMemberAndCards == null))
                {
                    _tbMemberAndCards = base.CreateObjectSet<tbMemberAndCard>("tbMemberAndCards");
                }
                return _tbMemberAndCards;
            }
        }
        private ObjectSet<tbMemberAndCard> _tbMemberAndCards;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tbMemberInfo> tbMemberInfoes
        {
            get
            {
                if ((_tbMemberInfoes == null))
                {
                    _tbMemberInfoes = base.CreateObjectSet<tbMemberInfo>("tbMemberInfoes");
                }
                return _tbMemberInfoes;
            }
        }
        private ObjectSet<tbMemberInfo> _tbMemberInfoes;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tbMemberScore> tbMemberScores
        {
            get
            {
                if ((_tbMemberScores == null))
                {
                    _tbMemberScores = base.CreateObjectSet<tbMemberScore>("tbMemberScores");
                }
                return _tbMemberScores;
            }
        }
        private ObjectSet<tbMemberScore> _tbMemberScores;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tbCards EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotbCards(tbCard tbCard)
        {
            base.AddObject("tbCards", tbCard);
        }
    
        /// <summary>
        /// 將新物件加入 tbMembers EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotbMembers(tbMember tbMember)
        {
            base.AddObject("tbMembers", tbMember);
        }
    
        /// <summary>
        /// 將新物件加入 tbMemberAndCards EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotbMemberAndCards(tbMemberAndCard tbMemberAndCard)
        {
            base.AddObject("tbMemberAndCards", tbMemberAndCard);
        }
    
        /// <summary>
        /// 將新物件加入 tbMemberInfoes EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotbMemberInfoes(tbMemberInfo tbMemberInfo)
        {
            base.AddObject("tbMemberInfoes", tbMemberInfo);
        }
    
        /// <summary>
        /// 將新物件加入 tbMemberScores EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotbMemberScores(tbMemberScore tbMemberScore)
        {
            base.AddObject("tbMemberScores", tbMemberScore);
        }

        #endregion

    }

    #endregion

    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WheatDBModel", Name="tbCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbCard : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tbCard 物件。
        /// </summary>
        /// <param name="cardID">CardID 屬性的初始值。</param>
        public static tbCard CreatetbCard(global::System.Int32 cardID)
        {
            tbCard tbCard = new tbCard();
            tbCard.CardID = cardID;
            return tbCard;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardID
        {
            get
            {
                return _CardID;
            }
            set
            {
                if (_CardID != value)
                {
                    OnCardIDChanging(value);
                    ReportPropertyChanging("CardID");
                    _CardID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardID");
                    OnCardIDChanged();
                }
            }
        }
        private global::System.Int32 _CardID;
        partial void OnCardIDChanging(global::System.Int32 value);
        partial void OnCardIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNumber
        {
            get
            {
                return _CardNumber;
            }
            set
            {
                OnCardNumberChanging(value);
                ReportPropertyChanging("CardNumber");
                _CardNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNumber");
                OnCardNumberChanged();
            }
        }
        private global::System.String _CardNumber;
        partial void OnCardNumberChanging(global::System.String value);
        partial void OnCardNumberChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardKey
        {
            get
            {
                return _CardKey;
            }
            set
            {
                OnCardKeyChanging(value);
                ReportPropertyChanging("CardKey");
                _CardKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardKey");
                OnCardKeyChanged();
            }
        }
        private global::System.String _CardKey;
        partial void OnCardKeyChanging(global::System.String value);
        partial void OnCardKeyChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cardstate
        {
            get
            {
                return _Cardstate;
            }
            set
            {
                OnCardstateChanging(value);
                ReportPropertyChanging("Cardstate");
                _Cardstate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cardstate");
                OnCardstateChanged();
            }
        }
        private Nullable<global::System.Int32> _Cardstate;
        partial void OnCardstateChanging(Nullable<global::System.Int32> value);
        partial void OnCardstateChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberAndCard_tbCard", "tbMemberAndCard")]
        public EntityCollection<tbMemberAndCard> tbMemberAndCards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbMemberAndCard>("WheatDBModel.FK_tbMemberAndCard_tbCard", "tbMemberAndCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbMemberAndCard>("WheatDBModel.FK_tbMemberAndCard_tbCard", "tbMemberAndCard", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WheatDBModel", Name="tbMember")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbMember : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tbMember 物件。
        /// </summary>
        /// <param name="memberID">MemberID 屬性的初始值。</param>
        public static tbMember CreatetbMember(global::System.Guid memberID)
        {
            tbMember tbMember = new tbMember();
            tbMember.MemberID = memberID;
            return tbMember;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Guid _MemberID;
        partial void OnMemberIDChanging(global::System.Guid value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegisterTime
        {
            get
            {
                return _RegisterTime;
            }
            set
            {
                OnRegisterTimeChanging(value);
                ReportPropertyChanging("RegisterTime");
                _RegisterTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegisterTime");
                OnRegisterTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegisterTime;
        partial void OnRegisterTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnRegisterTimeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginTime
        {
            get
            {
                return _LastLoginTime;
            }
            set
            {
                OnLastLoginTimeChanging(value);
                ReportPropertyChanging("LastLoginTime");
                _LastLoginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginTime");
                OnLastLoginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginTime;
        partial void OnLastLoginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginTimeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Del
        {
            get
            {
                return _Del;
            }
            set
            {
                OnDelChanging(value);
                ReportPropertyChanging("Del");
                _Del = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Del");
                OnDelChanged();
            }
        }
        private Nullable<global::System.Boolean> _Del;
        partial void OnDelChanging(Nullable<global::System.Boolean> value);
        partial void OnDelChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Lock
        {
            get
            {
                return _Lock;
            }
            set
            {
                OnLockChanging(value);
                ReportPropertyChanging("Lock");
                _Lock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lock");
                OnLockChanged();
            }
        }
        private Nullable<global::System.Boolean> _Lock;
        partial void OnLockChanging(Nullable<global::System.Boolean> value);
        partial void OnLockChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberAndCard_tbMember1", "tbMemberAndCard")]
        public EntityCollection<tbMemberAndCard> tbMemberAndCards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbMemberAndCard>("WheatDBModel.FK_tbMemberAndCard_tbMember1", "tbMemberAndCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbMemberAndCard>("WheatDBModel.FK_tbMemberAndCard_tbMember1", "tbMemberAndCard", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberInfo_tbMember", "tbMemberInfo")]
        public EntityCollection<tbMemberInfo> tbMemberInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbMemberInfo>("WheatDBModel.FK_tbMemberInfo_tbMember", "tbMemberInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbMemberInfo>("WheatDBModel.FK_tbMemberInfo_tbMember", "tbMemberInfo", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberScore_tbMember", "tbMemberScore")]
        public EntityCollection<tbMemberScore> tbMemberScores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbMemberScore>("WheatDBModel.FK_tbMemberScore_tbMember", "tbMemberScore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbMemberScore>("WheatDBModel.FK_tbMemberScore_tbMember", "tbMemberScore", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WheatDBModel", Name="tbMemberAndCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbMemberAndCard : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tbMemberAndCard 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        public static tbMemberAndCard CreatetbMemberAndCard(global::System.Int32 id)
        {
            tbMemberAndCard tbMemberAndCard = new tbMemberAndCard();
            tbMemberAndCard.id = id;
            return tbMemberAndCard;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                OnMemberIDChanging(value);
                ReportPropertyChanging("MemberID");
                _MemberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberID");
                OnMemberIDChanged();
            }
        }
        private Nullable<global::System.Guid> _MemberID;
        partial void OnMemberIDChanging(Nullable<global::System.Guid> value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardID
        {
            get
            {
                return _CardID;
            }
            set
            {
                OnCardIDChanging(value);
                ReportPropertyChanging("CardID");
                _CardID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardID");
                OnCardIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CardID;
        partial void OnCardIDChanging(Nullable<global::System.Int32> value);
        partial void OnCardIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Del
        {
            get
            {
                return _Del;
            }
            set
            {
                OnDelChanging(value);
                ReportPropertyChanging("Del");
                _Del = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Del");
                OnDelChanged();
            }
        }
        private Nullable<global::System.Boolean> _Del;
        partial void OnDelChanging(Nullable<global::System.Boolean> value);
        partial void OnDelChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberAndCard_tbCard", "tbCard")]
        public tbCard tbCard
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbCard>("WheatDBModel.FK_tbMemberAndCard_tbCard", "tbCard").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbCard>("WheatDBModel.FK_tbMemberAndCard_tbCard", "tbCard").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbCard> tbCardReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbCard>("WheatDBModel.FK_tbMemberAndCard_tbCard", "tbCard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbCard>("WheatDBModel.FK_tbMemberAndCard_tbCard", "tbCard", value);
                }
            }
        }
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberAndCard_tbMember1", "tbMember")]
        public tbMember tbMember
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberAndCard_tbMember1", "tbMember").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberAndCard_tbMember1", "tbMember").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbMember> tbMemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberAndCard_tbMember1", "tbMember");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbMember>("WheatDBModel.FK_tbMemberAndCard_tbMember1", "tbMember", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WheatDBModel", Name="tbMemberInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbMemberInfo : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tbMemberInfo 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        public static tbMemberInfo CreatetbMemberInfo(global::System.Int32 id)
        {
            tbMemberInfo tbMemberInfo = new tbMemberInfo();
            tbMemberInfo.id = id;
            return tbMemberInfo;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                OnMemberIDChanging(value);
                ReportPropertyChanging("MemberID");
                _MemberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberID");
                OnMemberIDChanged();
            }
        }
        private Nullable<global::System.Guid> _MemberID;
        partial void OnMemberIDChanging(Nullable<global::System.Guid> value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FristName
        {
            get
            {
                return _FristName;
            }
            set
            {
                OnFristNameChanging(value);
                ReportPropertyChanging("FristName");
                _FristName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FristName");
                OnFristNameChanged();
            }
        }
        private global::System.String _FristName;
        partial void OnFristNameChanging(global::System.String value);
        partial void OnFristNameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private Nullable<global::System.Int32> _Sex;
        partial void OnSexChanging(Nullable<global::System.Int32> value);
        partial void OnSexChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private global::System.String _Birthday;
        partial void OnBirthdayChanging(global::System.String value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IDCard
        {
            get
            {
                return _IDCard;
            }
            set
            {
                OnIDCardChanging(value);
                ReportPropertyChanging("IDCard");
                _IDCard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IDCard");
                OnIDCardChanged();
            }
        }
        private global::System.String _IDCard;
        partial void OnIDCardChanging(global::System.String value);
        partial void OnIDCardChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DetailedAddress
        {
            get
            {
                return _DetailedAddress;
            }
            set
            {
                OnDetailedAddressChanging(value);
                ReportPropertyChanging("DetailedAddress");
                _DetailedAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DetailedAddress");
                OnDetailedAddressChanged();
            }
        }
        private global::System.String _DetailedAddress;
        partial void OnDetailedAddressChanging(global::System.String value);
        partial void OnDetailedAddressChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberInfo_tbMember", "tbMember")]
        public tbMember tbMember
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberInfo_tbMember", "tbMember").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberInfo_tbMember", "tbMember").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbMember> tbMemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberInfo_tbMember", "tbMember");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbMember>("WheatDBModel.FK_tbMemberInfo_tbMember", "tbMember", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WheatDBModel", Name="tbMemberScore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbMemberScore : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tbMemberScore 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        public static tbMemberScore CreatetbMemberScore(global::System.Int32 id)
        {
            tbMemberScore tbMemberScore = new tbMemberScore();
            tbMemberScore.id = id;
            return tbMemberScore;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                OnMemberIDChanging(value);
                ReportPropertyChanging("MemberID");
                _MemberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberID");
                OnMemberIDChanged();
            }
        }
        private Nullable<global::System.Guid> _MemberID;
        partial void OnMemberIDChanging(Nullable<global::System.Guid> value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Score
        {
            get
            {
                return _Score;
            }
            set
            {
                OnScoreChanging(value);
                ReportPropertyChanging("Score");
                _Score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Score");
                OnScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _Score;
        partial void OnScoreChanging(Nullable<global::System.Int32> value);
        partial void OnScoreChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bread
        {
            get
            {
                return _Bread;
            }
            set
            {
                OnBreadChanging(value);
                ReportPropertyChanging("Bread");
                _Bread = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bread");
                OnBreadChanged();
            }
        }
        private Nullable<global::System.Int32> _Bread;
        partial void OnBreadChanging(Nullable<global::System.Int32> value);
        partial void OnBreadChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WheatDBModel", "FK_tbMemberScore_tbMember", "tbMember")]
        public tbMember tbMember
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberScore_tbMember", "tbMember").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberScore_tbMember", "tbMember").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbMember> tbMemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbMember>("WheatDBModel.FK_tbMemberScore_tbMember", "tbMember");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbMember>("WheatDBModel.FK_tbMemberScore_tbMember", "tbMember", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
